/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Person.Person;
import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;

    public AdminUserAccount(UserAccount sua, JPanel jp) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        initComponents();
        //display user details here
        String tpn = selecteduseraccount.getPersonId();
        String tr= selecteduseraccount.getRole();
        String tid= selecteduseraccount.getUserLoginName();
        txtipn.setText(tpn);
        txtr.setText(tr);
        txtid.setText(tid);
        txtid.setEnabled(false);
        txtid1.setEnabled(false);
        Btnsave.setEnabled(false);

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        Btnmodify = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        Btnsave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtipn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtr = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 255, 255));
        setLayout(null);

        Back.setText("Update>>");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(490, 410, 100, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Administer User Account");
        add(jLabel2);
        jLabel2.setBounds(180, 40, 280, 28);

        Back1.setText("<< Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        add(Back1);
        Back1.setBounds(20, 20, 100, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("UserName: ");
        add(jLabel1);
        jLabel1.setBounds(130, 190, 150, 40);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        add(txtid);
        txtid.setBounds(260, 200, 170, 30);

        Btnmodify.setText("Modify");
        Btnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmodifyActionPerformed(evt);
            }
        });
        add(Btnmodify);
        Btnmodify.setBounds(260, 310, 80, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Password: ");
        add(jLabel3);
        jLabel3.setBounds(140, 240, 100, 40);

        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        add(txtid1);
        txtid1.setBounds(260, 250, 170, 30);

        Btnsave.setText("Save");
        Btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsaveActionPerformed(evt);
            }
        });
        add(Btnsave);
        Btnsave.setBounds(360, 310, 70, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Person Name: ");
        add(jLabel4);
        jLabel4.setBounds(110, 100, 150, 40);

        txtipn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipnActionPerformed(evt);
            }
        });
        add(txtipn);
        txtipn.setBounds(260, 100, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Role: ");
        add(jLabel5);
        jLabel5.setBounds(180, 140, 80, 40);

        txtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrActionPerformed(evt);
            }
        });
        add(txtr);
        txtr.setBounds(260, 150, 170, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_Back1ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void BtnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmodifyActionPerformed
        // TODO add your handling code here:
        String tid = txtipn.getText();
        String tr= txtr.getText();
        String tu= txtid.getText();
        selecteduseraccount.getAssociatedPersonProfile().getPerson().setId(tid);
        selecteduseraccount.getAssociatedPersonProfile().getPerson().setRole(tr);
//        selecteduseraccount.
        txtid.setEnabled(true);
        txtid1.setEnabled(true);
        Btnsave.setEnabled(true);

    }//GEN-LAST:event_BtnmodifyActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void BtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsaveActionPerformed
        // TODO add your handling code here:
        
        txtid.setEnabled(false);
        txtid1.setEnabled(false);
        Btnsave.setEnabled(false);
    }//GEN-LAST:event_BtnsaveActionPerformed

    private void txtipnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipnActionPerformed

    private void txtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton Btnmodify;
    private javax.swing.JButton Btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtipn;
    private javax.swing.JTextField txtr;
    // End of variables declaration//GEN-END:variables

}
