/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;
import homework.ViewB;
import homework.ViewH;
import homework.ViewL;
import homework.ViewP;
/**
 *
 * @author Ram
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    ViewB bankaccount;
    ViewH homeaddress;
    ViewL localaddress;
    ViewP person;
    public MainJFrame() {
        initComponents();
        bankaccount = new ViewB();
        homeaddress = new ViewH();
        localaddress = new ViewL();
        person = new ViewP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Side = new javax.swing.JPanel();
        BtnCP = new javax.swing.JButton();
        BtnCH = new javax.swing.JButton();
        BtnVP = new javax.swing.JButton();
        BtnVH = new javax.swing.JButton();
        BtnCB = new javax.swing.JButton();
        BtnVL = new javax.swing.JButton();
        BtnCL = new javax.swing.JButton();
        BtnVB = new javax.swing.JButton();
        Main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Side.setBackground(new java.awt.Color(255, 255, 255));

        BtnCP.setText("Create Person");
        BtnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCPActionPerformed(evt);
            }
        });

        BtnCH.setText("Create Home address");
        BtnCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCHActionPerformed(evt);
            }
        });

        BtnVP.setText("View Person");
        BtnVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVPActionPerformed(evt);
            }
        });

        BtnVH.setText("View Home address");
        BtnVH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVHActionPerformed(evt);
            }
        });

        BtnCB.setText("Create Bank Account");
        BtnCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCBActionPerformed(evt);
            }
        });

        BtnVL.setText("View Local address");
        BtnVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVLActionPerformed(evt);
            }
        });

        BtnCL.setText("Create Local address");
        BtnCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCLActionPerformed(evt);
            }
        });

        BtnVB.setText("View Bank Account");
        BtnVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideLayout = new javax.swing.GroupLayout(Side);
        Side.setLayout(SideLayout);
        SideLayout.setHorizontalGroup(
            SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SideLayout.createSequentialGroup()
                        .addGroup(SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCP)
                            .addComponent(BtnCH, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SideLayout.setVerticalGroup(
            SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BtnCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVP)
                .addGap(15, 15, 15)
                .addComponent(BtnCH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVB)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(Side);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCPActionPerformed
        // TODO add your handling code here:
        CP cp= new CP(person);
        jSplitPane1.setRightComponent(cp);
    }//GEN-LAST:event_BtnCPActionPerformed

    private void BtnCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCHActionPerformed
        // TODO add your handling code here:
        CH ch= new CH(homeaddress);
        jSplitPane1.setRightComponent(ch);
    }//GEN-LAST:event_BtnCHActionPerformed

    private void BtnVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVPActionPerformed
        // TODO add your handling code here:
        VP vp= new VP(person);
        jSplitPane1.setRightComponent(vp);
        
    }//GEN-LAST:event_BtnVPActionPerformed

    private void BtnVHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVHActionPerformed
        // TODO add your handling code here:
        VH vh= new VH(homeaddress);
        jSplitPane1.setRightComponent(vh);
    }//GEN-LAST:event_BtnVHActionPerformed

    private void BtnCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCBActionPerformed
        // TODO add your handling code here:
        CB cb= new CB(bankaccount);
        jSplitPane1.setRightComponent(cb);
    }//GEN-LAST:event_BtnCBActionPerformed

    private void BtnVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVLActionPerformed
        // TODO add your handling code here:
        VL viewPanel= new VL(localaddress);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_BtnVLActionPerformed

    private void BtnCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCLActionPerformed
        // TODO add your handling code here:
        CL cl= new CL(localaddress);
        jSplitPane1.setRightComponent(cl);
    }//GEN-LAST:event_BtnCLActionPerformed

    private void BtnVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVBActionPerformed
        // TODO add your handling code here:
        VB vb= new VB(bankaccount);
        jSplitPane1.setRightComponent(vb);
    }//GEN-LAST:event_BtnVBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCB;
    private javax.swing.JButton BtnCH;
    private javax.swing.JButton BtnCL;
    private javax.swing.JButton BtnCP;
    private javax.swing.JButton BtnVB;
    private javax.swing.JButton BtnVH;
    private javax.swing.JButton BtnVL;
    private javax.swing.JButton BtnVP;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Side;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
